import Automotives from '@/components/servicesPage/automotives/Automotives';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Felsunny Technology | Electric Vehicle Sales in Nigeria',
  description:
    'Discover top electric vehicles with Felsunny Technology. We specialize in EV sales, sustainable transport solutions, and smart driving innovations across Nigeria and globally.',
  keywords: [
    'felsunny',
    'felsunny technology',
    'felix sunday ayeniko',
    'ayeniko',
    'felsunny tech',
    'electric vehicles Nigeria',
    'EVs for sale Nigeria',
    'buy electric cars Nigeria',
    'sustainable transport Nigeria',
    'green vehicles Nigeria',
    'zero emission vehicles',
    'eco-friendly cars',
    'electric cars Lagos',
    'EV dealership Nigeria',
    'VoltDrive Nigeria',
    'smart driving',
    'Tesla Nigeria',
    'Nissan Leaf Nigeria',
    'electric SUVs',
    'EV technology',
    'regenerative braking',
    'autonomous electric cars',
    'electric vehicle incentives',
    'Nigeria EV incentives',
    'solar EV charging',
    'clean energy cars',
    'environmentally friendly cars',
    'EV cost savings',
    'electric mobility',
    'EV maintenance',
    'charging infrastructure Nigeria',
    'Ilorin electric vehicles',
    'Abuja EV market',
    'buy Tesla Nigeria',
    'EV dealership Abuja',
    'FCT EV sales',
    'Kwara State electric cars',
    'Gwarinpa cars',
    'affordable electric vehicles',
    'latest electric cars',
    'EV innovation',
    'go electric Nigeria',
    'EVs West Africa',
    'electric fleet Nigeria',
    'company fleet EV',
    'low emission vehicles',
    'green auto tech',
    'battery electric vehicles',
    'smart electric vehicles',
    'Felsunny EV',
    'eco driving',
    'best EV prices Nigeria',
    'EV adoption Nigeria',
    'Africa electric mobility',
    'sustainable vehicle solutions',
    'fleet electrification Nigeria',
    'green auto dealers',
    'plug-in vehicles',
    'zero emissions cars Nigeria',
    'fuel-free driving',
    'best electric cars 2025',
    'future of transport Nigeria',
    'e-mobility Nigeria',
    'EV service centers Nigeria',
    'EV test drive Nigeria',
    'luxury electric vehicles',
    'affordable EVs',
    'EV finance Nigeria',
    'EV trade-in',
    'electric car leasing',
    'electric mobility company',
    'green logistics',
    'electric trucks Nigeria',
    'e-cars Nigeria',
    'EV showroom Nigeria',
    'hybrid cars Nigeria',
    'EV tech startup Nigeria',
    'smart vehicle systems',
    'EV dealership Kwara',
    'Ilorin green cars',
    'Nigeria sustainable cars',
    'best EV dealership',
    'Felsunny Motors',
    'West Africa EV dealer',
    'Nigeria auto industry',
    'EV innovation Africa',
    'EV training Nigeria',
    'EV parts Nigeria',
    'electric cars for business',
    'fleet management EV',
    'Nigeria auto electrification',
    'Felsunny electric fleet',
    'government EV incentives',
    'car dealership Nigeria',
    'Nigerian EV market',
    'solar powered cars',
    'EV vehicle models',
    'electric sports cars',
    'EV awareness Nigeria',
    'green business transport',
    'EV promotion Nigeria',
    'EV logistics Nigeria',
    'Felsunny EV services',
    'Nigeria smart vehicles',
    'connected EVs',
    'electric hatchbacks',
    'charge points Nigeria',
    'fast charging stations',
    'EV buyers guide Nigeria',
    'electric sedan cars',
    'green energy transport',
    'auto technology Nigeria',
    'intelligent vehicle systems',
    'Nigeria vehicle exports',
    'EV customer reviews',
    'top EV brands Nigeria',
    'buy EVs online Nigeria',
    'Felsunny electric dealership',
    'EV mobility solutions',
    'Nigeria auto future',
    'EV green lifestyle',
    'Felsunny sustainability',
    'Abuja car dealers',
    'Ilorin auto sales',
    'online electric car shop',
    'solar vehicle Nigeria',
    'Nigerian EV distributors',
    'Nigerian green energy vehicles',
    'eco auto Nigeria',
    'clean car Nigeria',
    'global electric vehicles',
    'West Africa car sales',
    'Gwarinpa car dealership',
    'Nigeria vehicle sales',
    'green vehicle ownership',
    'sustainable future Nigeria',
    'Felsunny contact',
    'eco-conscious driving',
    'EV support Nigeria',
    'affordable eco cars',
    'Felsunny innovation',
    'EV Nigeria innovation',
    'drive electric Nigeria',
    'green driving Africa',
    'solar powered vehicle Nigeria',
    'smart EV Nigeria',
    'Felsunny auto tech',
    'EV solutions Nigeria',
    'battery powered cars',
    'Africa electric car market',
    'Nigerian auto innovation',
    'drive green Nigeria',
    'Abuja electric dealership',
    'EV test drive Ilorin',
    'green vehicle marketplace',
    'eco ride Nigeria',
    'Nigeria EV road map',
    'Felsunny customer stories',
    'smart driving systems',
    'Felsunny sustainability mission',
    'EV experts Nigeria',
    'Nigeria auto solutions',
    'electric mobility transition',
    'Felsunny motors Nigeria',
    'electric transport Nigeria',
    'next-gen vehicles',
    'clean energy transport',
    'car technology Nigeria',
    'electric trucks for business',
    'auto green future',
    'EV journey Nigeria',
    'Africa vehicle electrification',
    'smart energy vehicles',
    'ride electric with Felsunny',
    'EV charging Nigeria',
    'green movement Nigeria',
    'Felsunny drive smart',
    'affordable clean cars Nigeria',
    'solar EV innovation',
    'EV specialists Nigeria',
    'auto smart evolution',
    'EV purchase Nigeria',
    'Africa green tech',
    'electric vehicles export Nigeria',
    'Felsunny service excellence',
    'car sustainability goals',
    'Nigerian EV growth',
    'green vehicle trends',
    'sustainable dealerships',
    'Felsunny electric car guide',
    'affordable eco travel',
    'smart auto Africa',
    'clean driving Nigeria',
    'EV ownership benefits',
    'Felsunny vision',
    'green lifestyle driving',
    'electric mobility Nigeria 2025',
    'auto innovation leaders',
    'smart driving Africa',
    'tech powered cars Nigeria',
    'next-gen driving experience',
  ],
};

const page = () => {
  return <Automotives />;
};

export default page;
